version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: nutriflow_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: nutriflow_db
      POSTGRES_USER: nutriflow_user
      POSTGRES_PASSWORD: nutriflow_password_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - nutriflow_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nutriflow_user -d nutriflow_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutriflow_api
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://nutriflow_user:nutriflow_password_2024@db:5432/nutriflow_db
      DEBUG: "True"
      SECRET_KEY: "nutriflow-secret-key-development-2024"
      ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001"
    ports:
      - "8000:8000"
    networks:
      - nutriflow_network
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # Mount source code for development (remove in production)
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nutriflow_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nutriflow.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - nutriflow_network
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  nutriflow_network:
    driver: bridge
